defmodule Bed.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:identity, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
    end

    create unique_index(:identity, [:email], name: "identity_unique_email_index")

    create table(:bank_txn, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :amount, :decimal, null: false
      add :bank_account_id, :uuid
    end

    create table(:bank_account, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:bank_txn) do
      modify :bank_account_id,
             references(:bank_account,
               column: :id,
               name: "bank_txn_bank_account_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:bank_account) do
      add :nickname, :text, null: false
      add :balance, :decimal, null: false

      add :identity_id,
          references(:identity,
            column: :id,
            name: "bank_account_identity_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bank_account, "bank_account_identity_id_fkey")

    alter table(:bank_account) do
      remove :identity_id
      remove :balance
      remove :nickname
    end

    drop constraint(:bank_txn, "bank_txn_bank_account_id_fkey")

    alter table(:bank_txn) do
      modify :bank_account_id, :uuid
    end

    drop table(:bank_account)

    drop table(:bank_txn)

    drop_if_exists unique_index(:identity, [:email], name: "identity_unique_email_index")

    drop table(:identity)

    drop table(:tokens)
  end
end