defmodule Itch.Repo.Migrations.Genesis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:anniversary, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :citext, null: false
      add :date, :date, null: false
      add :calendar_kind, :text, null: false
    end
  end

  def down do
    drop table(:anniversary)
  end
end
