defmodule Itch.Repo.Migrations.Genesis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:anniversary, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :citext, null: false
      add :month, :bigint, null: false
      add :day, :bigint, null: false
      add :calendar_kind, :text, null: false
    end

    create unique_index(:anniversary, [:name], name: "anniversary_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:anniversary, [:name], name: "anniversary_unique_name_index")

    drop table(:anniversary)
  end
end